### ISSUE TITLE
Domínio breno.dev

### ISSUE THREAD

**Issue by brenopoggiali** [bzeymer/website#1]
Mano, vc planeja continuar esse projeto e manter esse domínio? heheh

**Comment by bzeymer** [comment]
Opa xará! beleza?

Então, planejo sim, na verdade eh algo q já está em desenvolvimento, mas
vou fazendo aos poucos.

Em qui., 13 de ago. de 2020 às 20:12, Breno Poggiali de Sousa <
notifications@github.com> escreveu:

**Comment by brenopoggiali** [comment]
Ah, legal! Mandou mto bem na compra do domínio 😁
Valeu pela resposta!!
